---
trigger:
  name: triggerRelease
  identifier: triggerRelease
  enabled: true
  stagesToExecute: []
  description: ""
  tags: {}
  encryptedWebhookSecretIdentifier: ""
  orgIdentifier: No_Code_Apps
  projectIdentifier: recipeforecasticreactic
  pipelineIdentifier: communityRelease
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: Release
        spec:
          connectorRef: account.svc_harness_git1
          autoAbortPreviousExecutions: false
          payloadConditions:
            - key: <+eventPayload.release.target_commitish>
              operator: Regex
              value: (main|release\/.+)
          headerConditions: []
          repoName: recipe-forecastic-reactic
          actions:
            - Publish
  pipelineBranchName: <+trigger.branch>
